### ISSUE TITLE
invalid type: string "fat", expected a boolean for key `profile.bench.lto`

### ISSUE THREAD

**Issue by adfi** [messense/fasttext-serving#7]
Hi,

It tried to install using `cargo install ...` but received this error:

`
error: failed to compile "fasttext-serving v0.5.4", intermediate artifacts can be found at "/tmp/cargo-install.n8Ja
0i7W5Z7K"
Caused by:
  unable to get packages from source
Caused by:
  failed to parse manifest at "/root/.cargo/registry/src/github.com-1ecc6299db9ec823/ahash-0.2.18/Cargo.toml"
Caused by:
  invalid type: string "fat", expected a boolean for key "profile.bench.lto"
`

I'm running this on a VM with OS Linux 4.9.0-9-amd64 #1 SMP Debian 4.9.168-1+deb9u2 (2019-05-13) x86_64

Any help is appreciated.

**Comment by messense** [comment]
Maybe try upgrading your rustc version to latest stable? Run `rustup update stable`

**Comment by adfi** [comment]
Thanks, I think that made a difference. Also had to install `cmake` to get past another hurdle. 

Now I'm getting the following error:

error[E0425]: cannot find value `VERSION_2_7_0` in crate `protobuf`
  --> /home/adnan_fiaz/.cargo/registry/src/github.com-1ecc6299db9ec823/fasttext-serving-0.5.4/src/grpc/predict.rs:27:49
   |
27 | const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_2_7_0;
   |                                                 ^^^^^^^^^^^^^ help: a constant with a similar name exists: `VERSION_2_8_1`

Hope you can help me with this one as well.

**Comment by messense** [comment]
Try `cargo install --version 0.6.0-alpha.1 fasttext-serving` to install the latest alpha release.

**Comment by messense** [comment]
@adfi Is your issue solved?

**Comment by adfi** [comment]
Almost! The installation was succesful. However when testing using your example with curl (from the README) it returned `App data is not configured, to configure use App::data()`.

**Comment by messense** [comment]
It seem that `actix-web` changed something, you can try the grpc server.

https://github.com/messense/fasttext-serving#serve-grpc-api

**Comment by adfi** [comment]
That worked fine up until the part where I ask it to make predictions. The server throws the following error: `thread 'tokio-runtime-worker' panicked at 'predict failed: "Model needs to be supervised for prediction!"', src/libcore/result.rs:1165:5`

Is there a specific model file I need to pass it? I'm using https://dl.fbaipublicfiles.com/fasttext/vectors-wiki/wiki.en.zip which includes the model bin file.

**Comment by messense** [comment]
The error message is clear: the model isn't supervised, can't be used for prediction.

**Comment by messense** [comment]
@adfi See 
https://github.com/facebookresearch/fastText/blob/d0bf803d4cdc4c763d73c907f21b2fab0ede355e/src/fasttext.cc#L432

**Comment by messense** [comment]
HTTP API fixed in 0.6.0-alpha.2, try `cargo install --version 0.6.0-alpha.2 fasttext-serving`.

For the prediction issue, try this model https://github.com/messense/fasttext-serving/blob/master/models/cooking.model.bin , see if it works.

**Comment by adfi** [comment]
Yes! that worked :-) Thanks for all the help. 

I assume to get the pre-trained vectors to work I would need to add an endpoint for the `getSentenceVector` function. Can you point me to where in your code you call the `FastText::predict` function as an example?

**Comment by messense** [comment]
Please open a new issue for the `getSentenceVector` endpoint, I'll get the implementation done.
